apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: configmaps-base

resources:
  - configmap-auth.yaml
  - configmap-matchmaking.yaml
  - configmap-frontend.yaml
  - configmap-infrastructure.yaml
