# Gestion des Classes de Stockage
# DÃ©finit les types de disques disponibles (Drivers).

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - standard.yaml
  - fast-ssd.yaml
