# Gestionnaire des Applications Métier
# Ce fichier centralise le déploiement de tous les microservices qui composent votre projet.
# Chaque dossier référencé ici doit contenir ses propres fichiers Kubernetes (Deployment, Service, etc.)

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: applications-base

resources:
  # Application Frontend (React/Vite)
  # Servi par un serveur web (ex: Nginx)
  - frontend/

  # Service d'Authentification (NestJS)
  # Gère l'inscription, le login, l'OAuth et les JWT
  - auth/

  # Service de Matchmaking (NestJS)
  # Gère la file d'attente, l'algorithme de rencontre et le WebSocket
  - matchmaking/
