# Module du Service de Matchmaking
# Ce fichier devra référencer les ressources Kubernetes pour le Matchmaking :
# - Deployment (Gestion des sockets et logique de jeu)
# - Service (Exposition des ports HTTP et WebSocket)

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: matchmaking-base

resources:
  # TODO: Ajouter les fichiers de ressources une fois créés
  # - deployment.yaml
  # - service.yaml
