apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: storage-base

resources:
  - storageclass-standard.yaml
  - storageclass-fast-ssd.yaml
  - pvc-auth-db.yaml
  - pvc-matchmaking-db.yaml
