apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: redis-base

resources:
  - secret.yaml

helmCharts:
  - name: redis
    repo: https://charts.bitnami.com/bitnami
    version: 18.0.1 # Vérifier version récente compatible
    releaseName: redis
    namespace: ft-transcendence # Sera surchargé par l'overlay
    valuesFile: values.yaml
