# Secret Redis Temporaire (Avant migration Vault)
# Ce fichier fournit un secret par défaut (mot de passe vide) pour permettre le déploiement
# de Redis en environnement de développement ou avant la mise en place de Vault.

# ATTENTION :
# 1. En PROD, ce fichier sera remplacé par un 'ExternalSecret' connecté à Vault.
# 2. Ne JAMAIS commiter de vrais mots de passe ici.

apiVersion: v1
kind: Secret
metadata:
  name: redis-secret
  labels:
    app: redis
    app.kubernetes.io/name: ft-transcendence
    app.kubernetes.io/part-of: ft-transcendence
    app.kubernetes.io/component: redis
type: Opaque
stringData:
  # Mot de passe vide par défaut pour le développement local
  password: ''
