apiVersion: v1
kind: Secret
metadata:
  name: redis-secret
  labels:
    app: redis
    app.kubernetes.io/name: ft-transcendence
    app.kubernetes.io/part-of: ft-transcendence
    app.kubernetes.io/component: redis
type: Opaque
stringData:
  password: ''
# Note: Le mot de passe Redis est vide par défaut
# Pour la production, il faudra créer le secret avec un mot de passe sécurisé
# via Vault ou un autre système de gestion de secrets
