apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: rabbitmq-base

resources:
  - secret.yaml

helmCharts:
  - name: rabbitmq
    repo: https://charts.bitnami.com/bitnami
    version: 12.0.0 # Vérifier version récente
    releaseName: rabbitmq
    namespace: ft-transcendence
    valuesFile: values.yaml
