apiVersion: v1
kind: ConfigMap
metadata:
  name: auth-config
data:
  LOG_LEVEL: "warn"
  REDIRECT_URI: "https://ft-transcendence.example.com"
  USER_SERVICE_URL: "http://auth-service.ft-transcendence-production.svc.cluster.local:3000"
  MATCHMAKING_SERVICE_URL: "http://matchmaking-service.ft-transcendence-production.svc.cluster.local:3001"
