apiVersion: v1
kind: ConfigMap
metadata:
  name: matchmaking-config
data:
  LOG_LEVEL: "warn"
  USER_SERVICE_URL: "http://auth-service.ft-transcendence-production.svc.cluster.local:3000"
  GAME_SERVICE_URL: "http://game-service.ft-transcendence-production.svc.cluster.local:3002"
