apiVersion: v1
kind: ConfigMap
metadata:
  name: frontend-config
data:
  VITE_APP_ENV: "production"
  VITE_API_URL: "https://api.ft-transcendence.example.com"
  VITE_AUTH_SERVICE_URL: "https://api.ft-transcendence.example.com/auth"
  VITE_MATCHMAKING_SERVICE_URL: "https://api.ft-transcendence.example.com/matchmaking"
  VITE_GAME_SERVICE_URL: "https://api.ft-transcendence.example.com/game"
  VITE_WS_URL: "wss://api.ft-transcendence.example.com"
