apiVersion: v1
kind: LimitRange
metadata:
  name: production-limits
  namespace: ft-transcendence-production
  labels:
    app.kubernetes.io/name: ft-transcendence
    app.kubernetes.io/part-of: ft-transcendence
    app.kubernetes.io/component: limit-range
    environment: production
spec:
  limits:
    - default:
        memory: '512Mi'
        cpu: '500m'
      defaultRequest:
        memory: '256Mi'
        cpu: '250m'
      max:
        memory: '4Gi'
        cpu: '4'
      min:
        memory: '128Mi'
        cpu: '100m'
      type: Container
