apiVersion: v1
kind: ConfigMap
metadata:
  name: matchmaking-config
data:
  LOG_LEVEL: "debug"
  MATCHMAKING_TICK_RATE_MS: "1000"
  USER_SERVICE_URL: "http://auth-service.ft-transcendence-dev.svc.cluster.local:3000"
  GAME_SERVICE_URL: "http://game-service.ft-transcendence-dev.svc.cluster.local:3002"
