apiVersion: v1
kind: ConfigMap
metadata:
  name: auth-config
data:
  LOG_LEVEL: "debug"
  REDIRECT_URI: "http://localhost:3000"
  USER_SERVICE_URL: "http://auth-service.ft-transcendence-dev.svc.cluster.local:3000"
  MATCHMAKING_SERVICE_URL: "http://matchmaking-service.ft-transcendence-dev.svc.cluster.local:3001"
