apiVersion: v1
kind: ConfigMap
metadata:
  name: frontend-config
  labels:
    app.kubernetes.io/name: ft-transcendence
    app.kubernetes.io/part-of: ft-transcendence
    app.kubernetes.io/component: frontend
    app.kubernetes.io/managed-by: kustomize
data:
  VITE_APP_ENV: 'development'
  VITE_API_URL: 'http://localhost:3000'
  VITE_AUTH_SERVICE_URL: 'http://localhost:3000'
  VITE_MATCHMAKING_SERVICE_URL: 'http://localhost:3001'
  VITE_GAME_SERVICE_URL: 'http://localhost:3002'
  VITE_WS_URL: 'ws://localhost:3001'
