# Configuration de l'Environnement de DÉVELOPPEMENT
# Cet overlay modifie la base pour créer un environnement léger, isolé et permissif.
# Usage : kustomize build infrastructure/k8s/overlays/dev | kubectl apply -f -

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: ft-transcendence-dev

namespace: ft-transcendence-dev

resources:
  - resources/namespace.yaml
  - resources/resource-quota.yaml
  - resources/limit-range.yaml
  - ../../base

patches:
  # --- Adaptation des ConfigMaps (Variables d'env) ---
  - target:
      kind: ConfigMap
      name: auth-config
    path: patches/auth/configmap-patch-auth.yaml
  - target:
      kind: ConfigMap
      name: matchmaking-config
    path: patches/matchmaking/configmap-patch-matchmaking.yaml
  - target:
      kind: ConfigMap
      name: frontend-config
    path: patches/frontend/configmap-patch-frontend.yaml

  # --- Adaptation du Stockage ---
  - target:
      kind: PersistentVolumeClaim
      name: auth-db-pvc
    path: patches/storage/storage-patch-auth.yaml
  - target:
      kind: PersistentVolumeClaim
      name: matchmaking-db-pvc
    path: patches/storage/storage-patch-matchmaking.yaml

  # --- Adaptation des Services Stateful (Redis/RabbitMQ) ---
  # Note: Les noms sont ceux générés par Helm avec fullnameOverride
  - target:
      kind: StatefulSet
      name: redis-master
    path: patches/redis/redis-patch.yaml
  - target:
      kind: StatefulSet
      name: rabbitmq
    path: patches/rabbitmq/rabbitmq-patch.yaml

  # Surcharge des Secrets (Placeholder -> Valeurs Dev explicites)
  - target:
      kind: Secret
      name: redis-secret
    path: resources/redis-secret.yaml
  - target:
      kind: Secret
      name: rabbitmq-secret
    path: resources/rabbitmq-secret.yaml

  # --- Adaptation Nginx ---
  - target:
      kind: Deployment
      name: nginx-ingress-ingress-nginx-controller
    path: patches/nginx/nginx-deployment-patch.yaml
  - target:
      kind: Service
      name: nginx-ingress-ingress-nginx-controller
    path: patches/nginx/nginx-service-patch.yaml
  - target:
      kind: ClusterRoleBinding
      name: nginx-ingress-ingress-nginx-controller
    path: patches/nginx/nginx-rbac-patch.yaml
