apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: ft-transcendence-dev

namespace: ft-transcendence-dev

resources:
  - ../../base
  - resource-quota.yaml
  - limit-range.yaml

patches:
  - path: namespace-patch-test.yaml
  - path: namespace-patch-production.yaml
  - path: configmap-patch-auth.yaml
  - path: configmap-patch-matchmaking.yaml
  - path: configmap-patch-frontend.yaml

configMapGenerator: []

secretGenerator: []
