apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: ft-transcendence-dev

namespace: ft-transcendence-dev

resources:
  - ../../base
  - namespace.yaml
  - resource-quota.yaml
  - limit-range.yaml

patches:
  - target:
      kind: ConfigMap
      name: auth-config
    path: configmap-patch-auth.yaml
  - target:
      kind: ConfigMap
      name: matchmaking-config
    path: configmap-patch-matchmaking.yaml
  - target:
      kind: ConfigMap
      name: frontend-config
    path: configmap-patch-frontend.yaml
  - target:
      kind: PersistentVolumeClaim
      name: auth-db-pvc
    path: storage-patch-auth.yaml
  - target:
      kind: PersistentVolumeClaim
      name: matchmaking-db-pvc
    path: storage-patch-matchmaking.yaml
  - target:
      kind: StatefulSet
      name: redis
    path: redis-patch.yaml

resources:
  - redis-secret.yaml

configMapGenerator:
  - name: redis-config
    files:
      - redis.conf
    options:
      labels:
        app: redis
        app.kubernetes.io/name: ft-transcendence
        app.kubernetes.io/part-of: ft-transcendence
        app.kubernetes.io/component: redis
      disableNameSuffixHash: false

secretGenerator: []
