apiVersion: v1
kind: LimitRange
metadata:
  name: dev-limits
  namespace: ft-transcendence-dev
  labels:
    app.kubernetes.io/name: ft-transcendence
    app.kubernetes.io/part-of: ft-transcendence
    app.kubernetes.io/component: limit-range
    environment: dev
spec:
  limits:
    - default:
        memory: '256Mi'
        cpu: '250m'
      defaultRequest:
        memory: '128Mi'
        cpu: '100m'
      max:
        memory: '512Mi'
        cpu: '500m'
      min:
        memory: '64Mi'
        cpu: '50m'
      type: Container
