apiVersion: v1
kind: Namespace
metadata:
  name: ft-transcendence-dev
  labels:
    name: ft-transcendence-dev
    environment: dev
    app.kubernetes.io/name: ft-transcendence
    app.kubernetes.io/part-of: ft-transcendence
    app.kubernetes.io/component: namespace
    pod-security.kubernetes.io/enforce: baseline
    pod-security.kubernetes.io/audit: baseline
    pod-security.kubernetes.io/warn: baseline
