apiVersion: v1
kind: ResourceQuota
metadata:
  name: dev-quota
  namespace: ft-transcendence-dev
  labels:
    app.kubernetes.io/name: ft-transcendence
    app.kubernetes.io/part-of: ft-transcendence
    app.kubernetes.io/component: resource-quota
    environment: dev
spec:
  hard:
    requests.cpu: '4'
    requests.memory: 8Gi
    limits.cpu: '8'
    limits.memory: 16Gi
    persistentvolumeclaims: '4'
    pods: '20'
    services.loadbalancers: '0'
    services.nodeports: '2'
