apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: nginx-ingress-base

helmCharts:
  - name: ingress-nginx
    repo: https://kubernetes.github.io/ingress-nginx
    version: 4.10.1 # Version correspondant Ã  controller v1.10.1 environ
    releaseName: nginx-ingress
    namespace: ft-transcendence
    valuesFile: values.yaml
