apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: nginx-base

resources:
  - serviceaccount.yaml
  - rbac.yaml
  - configmap.yaml
  - configmap-modsecurity.yaml
  - deployment.yaml
  - service.yaml
  - ingressclass.yaml
